env:
  browser: true
  es6: true
  commonjs: true
extends:
  - "plugin:@typescript-eslint/recommended"
plugins:
  - @typescript-eslint
  - prettier
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
settings:
  import/resolver: node
rules:
  prettier/prettier: error
